# Generated by Django 4.0.2 on 2022-03-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amaze',
            options={'ordering': ('differ', '-created')},
        ),
        migrations.RenameField(
            model_name='amaze',
            old_name='old_val',
            new_name='exp_val',
        ),
    ]
